version: '3.9'

x-tz: &default-tz
  TZ: Europe/Berlin
x-env: &default-env
  RAILS_ENV: ${RAILS_ENV:-development}
  NODE_ENV: ${NODE_ENV:-development}
  YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache

services:
  x-app: &app
    image: community_app:0.0.1
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION:-2.6.6}
        BUNDLER_VERSION: ${BUNDLER_VERSION:-2.2}
        NODE_VERSION: ${NODE_VERSION:-12.22}
        YARN_VERSION: ${YARN_VERSION:-1.19}
        POSTGRES_VERSION: ${POSTGRES_VERSION:-12.6}
    stdin_open: true
    tty: true
    environment: &app-env
      <<: *default-tz
      <<: *default-env
    tmpfs:
      - /tmp
    networks:
      - community_app

  web: &web
    <<: *app
    ports:
      - 3000:3000
    environment:
      <<: *app-env
      WEBPACKER_DEV_SERVER_HOST: webpacker
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-5}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432
      PSQL_HISTFILE: /app/log/.psql_history
      REDIS_URL: redis://redis:6379
      HISTFILE: /app/log/.sh_history
      EDITOR: vim
    volumes:
      - .:/app:cached
      - rails_cache_data:/app/tmp/cache
      - bundle_data:/usr/local/bundle
      - node_modules_data:/app/node_modules
      - packs_data:/app/public/packs
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    depends_on:
      - webpacker
      - postgres
      - redis
      - memcached

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      <<: *app-env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app:cached
      - bundle_data:/usr/local/bundle
      - node_modules_data:/app/node_modules
      - packs_data:/app/public/packs

  postgres:
    image: postgres:${postgres_version:-12.6}-alpine
    env_file: .env
    ports:
      - 5432:5432
    environment:
      <<: *default-tz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PSQL_HISTFILE: /root/log/.psql_history
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres_data:/var/lib/postgresql/data
      - ./log:/root/log:cached
    networks:
      - community_app
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -h postgres
      interval: 30s
      timeout: 3s
      retries: 3

  redis:
    image: redis:6.0.9-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    environment:
      <<: *default-tz
    volumes:
      - redis_data:/data
    networks:
      - community_app
    restart: unless-stopped
    healthcheck:
      test: redis-cli -h redis --pass ${REDIS_PASSWORD:-redis} ping
      interval: 30s
      timeout: 3s
      retries: 3

  memcached:
    image: memcached:1.6-alpine
    environment:
      <<: *default-tz
    networks:
      - community_app
    restart: unless-stopped

  test:
    <<: *app
    command: rails test
    environment:
      <<: *default-tz
      RAILS_ENV: test
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app:cached
      - bundle_data:/usr/local/bundle
      - node_modules_data:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  guard:
    <<: *app
    command: guard
    environment:
      <<: *app-env

volumes:
  rails_cache_data:
  bundle_data:
  node_modules_data:
  packs_data:
  postgres_data:
  redis_data:

networks:
  community_app:
    name: community_app
