version: '3.7'

x-tz: &default-tz
  TZ: Europe/Berlin
x-env: &default-env
  RAILS_ENV: ${RAILS_ENV:-development}
  NODE_ENV: ${NODE_ENV:-development}

services:
  x-app: &app
    image: community_app:0.0.1
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION:-2.6.6}
        BUNDLER_VERSION: ${BUNDLER_VERSION:-2.1.4}
        NODE_VERSION: ${NODE_VERSION:-12.21}
        YARN_VERSION: ${YARN_VERSION:-1.19}
        POSTGRES_VERSION: ${postgres_version:-12.6}
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache_data:/app/tmp/cache
      - bundle_data:/usr/local/bundle
      - node_modules_data:/app/node_modules
      - packs_data:/app/public/packs
    tmpfs:
      - /tmp
    networks:
      - community_app

  web: &web
    <<: *app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      <<: *default-tz
      <<: *default-env
      WEBPACKER_DEV_SERVER_HOST: webpacker
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/bootsnap
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-5}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432
      PSQL_HISTFILE: /app/log/.psql_history
      REDIS_URL: redis://redis:6379
      MEMCACHIER_SERVERS: memcached
      EDITOR: vim
    depends_on:
      - webpacker
      - postgres
      - redis
      - memcached

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      <<: *default-tz
      <<: *default-env
      WEBPACKER_DEV_SERVER_HOST: ${WEBPACKER_DEV_SERVER_HOST:-0.0.0.0}

  postgres:
    image: postgres:${postgres_version:-12.6}-alpine
    env_file: .env
    ports:
      - 5432:5432
    environment:
      <<: *default-tz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - community_app
    restart: unless-stopped

  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      <<: *default-tz
    volumes:
      - redis_data:/data
    networks:
      - community_app
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    environment:
      <<: *default-tz
    networks:
      - community_app
    restart: unless-stopped

  test:
    <<: *app
    command: rails test
    environment:
      <<: *default-tz
      RAILS_ENV: test
      NODE_ENV: test
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  guard:
    <<: *app
    command: guard
    environment:
      <<: *default-tz
      <<: *default-env

volumes:
  rails_cache_data:
  bundle_data:
  node_modules_data:
  packs_data:
  postgres_data:
  redis_data:

networks:
  community_app:
    name: community_app
