inherit_from: ../.rubocop.yml


Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Enabled: no

Metrics/AbcSize:
  Enabled: no

Metrics/MethodLength:
  Enabled: no